main: me.okay.coordsaver.CoordSaver
name: CoordSaver
version: 1.0
author: okay
api-version: 1.19

commands:
  globalcoords:
    description: "Manage global coordinates."
    usage: "/globalcoords"

  coords:
    description: "Manage your own coordinates."
    usage: "/coords"
  
permissions:
  coordsaver.admin:
    description: "Allows use of all CoordSaver commands."
    default: op
    children:
      coordsaver.globalcoords.set: true
      coordsaver.globalcoords.list: true
      coordsaver.globalcoords.remove: true
      coordsaver.globalcoords.clear: true
      coordsaver.coords.set: true
      coordsaver.coords.list: true
      coordsaver.coords.list.others: true
      coordsaver.coords.remove: true
      coordsaver.coords.clear: true
  
  coordsaver.globalcoords.set:
    description: "Allows players to set global coordinates."
    default: op
  
  coordsaver.globalcoords.list:
    description: "Allows players to list global coordinates."
    default: true
  
  coordsaver.globalcoords.remove:
    description: "Allows players to remove global coordinates."
    default: op
  
  coordsaver.globalcoords.clear:
    description: "Allows players to clear all global coordinates."
    default: op

  coordsaver.coords.set:
    description: "Allows players to set their own coordinates."
    default: true

  coordsaver.coords.list:
    description: "Allows players to list their own coordinates."
    default: true
    
  coordsaver.coords.list.others:
    description: "Allows players to view other players' coordinates."
    default: op

  coordsaver.coords.remove:
    description: "Allows players to remove their own coordinates."
    default: true
  
  coordsaver.coords.clear:
    description: "Allows players to clear all their own coordinates."
    default: true
